### PR TITLE
Fix Russian translation

### PR DESCRIPTION
**Pull request by andrewshadura**
Rewrite the Russian text to seem less like a machine translation

### CODE REVIEW

**Comment by clawfire** [comment]
Hey @andrewshadura 👋🏼

Thanks for helping but translation are managed by [a project on Crowdin](https://crowdin.com/project/covid19-passbook). It's easier because anyone can contribute and review other translations. Also it generate all the languages pages based on the index.html in english. 

If I accept this PR, your work will be lost in the next auto update in 24h.

May I kindly ask you to go [on the crowdin project](https://crowdin.com/project/covid19-passbook) to put your changes please ? 🙏🏼

**Comment by clawfire** [comment]
Also, for the language selector, just make your pr with the `index.html` file and all the others will be re-generated after based on it (I don't put the language name in the translation system since I want to keep it untranslated, in their original language.)

**Comment by andrewshadura** [comment]
> If I accept this PR, your work will be lost in the next auto update in 24h.
> 
> May I kindly ask you to go [on the crowdin project](https://crowdin.com/project/covid19-passbook) to put your changes please ? 

I uploaded my translation and created a bit of a mess, some sentences repeat twice 😕 I’m not sure how to fix it.

**Comment by clawfire** [comment]
To edit content in Russian, you can jump on that link directly https://crowdin.com/translate/covid19-passbook/7/en-ru?filter=basic&value=5
If you want to just proofread, go there https://crowdin.com/proofread/covid19-passbook/7/en-ru?filter=basic&value=34

**Comment by clawfire** [comment]
I've just undone your upload so it should be all fine now 😃

**Comment by andrewshadura** [comment]
Nooo, because I almost fixed it 😕 Can you un-undo it please?

**Comment by clawfire** [comment]
> Nooo, because I almost fixed it 😕 Can you un-undo it please?

I'm ... not quite sure.

**Comment by andrewshadura** [comment]
Okay, let’s not step on each other’s toes.

**Comment by andrewshadura** [comment]
Some of the translations can’t be automatically approved because they’re marked as "proofread", can you please have a look?

**Comment by andrewshadura** [comment]
Hi @clawfire, I have rebased this PR onto the current main just to see what else has been missing. I have also marked translations needing re-approval at CrowdIn by downvoting the currently approved one.

**Comment by andrewshadura** [comment]
Please also note the link to Google Play leads to the French page. I think it’s probably make sense to remove `hl=` parameter altogether.

**Comment by andrewshadura** [comment]
Done that in f14ce8c 🙂

**Comment by clawfire** [comment]
Hey thanks.
I’m in vacation right now but I’ll check that when I’ll be back ;)

Thanks for the work !
-- 
*Milan Thibault*
📝 clawfire.net • 🐦 @clawfire <https://twitter.com/clawfire> • 🗣 he/him

📱 I made a web app that lets you store your EU Covid Digital Certificate
into your phone wallets. It’s free, ad-free, tracking-free, open-source. Try
it now <https://covid19passbook.netlify.app/>!

**Comment by clawfire** [comment]
Ok so I reviewed on Crowdin and I think we are all good BUT, I still see an issue with the PR. 

you need to remove all "translations pages" (all pages except index.html) from the PR.
They are handled by Crowdin only. If you merge them, they will be override anyway in the minute.

**Comment by andrewshadura** [comment]
Sure, I'll drop them once I check the translations.
-- 
Cheers,
  Andrej

**Comment by andrewshadura** [comment]
@clawfire, it seem the new translations have been stuck on a separate branch for a couple of weeks?

**Comment by andrewshadura** [comment]
This bot is really annoying. @clawfire, could you please pull the translations in and put them on the right branch? My rebase of the remaining changes is blocked on that.

**Comment by andrewshadura** [comment]
Oh, and reopen this PR please.

**Pull request closed without merging**
