### PR TITLE
Feature/semantic theme - Last A11y improvements

### PR DESCRIPTION
**Pull request by geoffreycrofte**
Hello dear,

I get back the accessibility improvement from master to integrate everything into this branch and move forward on the new design.
Some stuff in random order:

- same content as the last one you had from me (#66)
- more colors in the color scheme (not sure yet we will need those if we are using color functions)
- last a11y color issues tackle down
- removed max-zoom on the viewport meta

I plan to work a little bit on the design proposed (#29) as soon as possible.

### CODE REVIEW

**Comment by clawfire** [comment]
I merged develop into the branch to be up to date with the latest changes

**Comment by clawfire** [comment]
I think we can kill that header don't you think? I mean ... It's kinda weird now just like this isn't it ?

**Comment by clawfire** [comment]
What do you think about it ? 😃

**Comment by geoffreycrofte** [comment]
> I merged develop into the branch to be up to date with the latest changes

I did that too yesterday to be sure I had an up-to-date branch :D 



> I think we can kill that header don't you think? I mean ... It's kinda weird now just like this isn't it ?

Yeah I kinda agree on the weird stacked header and sub headers.
But the European flag is reassuring I think, don't you think?

Should we propose a mix between Laurence's proposition and the addition of a flag or "european symbol" somewhere in the header?
I can propose something if you want :)

**Comment by clawfire** [comment]
Well, I really like what you did. The shield is re-assuring IMO. But if you want to go further please feel free.

**Pull request merged**
