### PR TITLE
Update eHN valuesets to 2.5.0

### LINKED ISSUE #360: [feature request] Update valueset
### Contact Details

_No response_

### Is your feature request related to a problem? Please describe.

I was trying to generate a card but it says my QR code not containing information needed. My vaccine is new on the product list https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/main/vaccine-medicinal-product.json#L152-L158 .

### Describe the solution you'd like

Update valueset to newer version. https://github.com/ehn-dcc-development/ehn-dcc-valuesets

### Describe alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tw0517tw**
https://github.com/ehn-dcc-development/ehn-dcc-valuesets/releases

fixes #360

### CODE REVIEW

**Review by clawfire — COMMENTED** [review]
Thanks for the updated default values 😃 

⚠️ I think the `test-type.json` is just a tab vs space conflict right ?

**Comment by tw0517tw** [comment]
In `test-type.json` there are some extra indent removed. What I did is only copy-paste the whole file from https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/main/test-type.json .

**Review by clawfire — APPROVED** [review]

**Comment by clawfire** [comment]
hey sorry @tw0517tw I had to revert the PR. I didn't see it but you made the PR to `main` and not `develop`

**Comment by clawfire** [comment]
I'll get your fix manually into `develop` but your contribution should be still visible on the repo 👍🏼 (as being part of the contributors)

**Comment by tw0517tw** [comment]
Thanks!

Sorry I didn't find that there is a develop branch.

**Pull request merged**
