### PR TITLE
iOS Webview/Safari detection

### LINKED ISSUE #25: [feature request] Display a message if iOS user comes with other browser than safari
**Is your feature request related to a problem? Please describe.**
Only safari on iOS allow to open a passbook. Chrome or Firefox fail to even download the file (i suspect iOS catch it and hide it)

**Describe the solution you'd like**
A message when we detect iOS user coming from anything than safari to warn them about the fact the save to wallet will not work could do the trick 

**Describe alternatives you've considered**
Feature detection would be better but I don't know any test for add to wallet capability.

### PR DESCRIPTION
**Pull request by grischard**
Fixes #25

### CODE REVIEW

**Comment by grischard** [comment]
This approach doesn't work.

Whitelisting Safari on iOS could work (until it doesn't).

Using https://www.npmjs.com/package/detect-inapp to blacklist well-known Webview user agents will probably cover the vast majority of cases.

**Comment by clawfire** [comment]
It's a bit early stage but I like the simplicity of your test so far. checking the npm package you mentionned

**Comment by clawfire** [comment]
Checked. The in-app seems promising but looking at the issues makes me thing it still collecting data to build their detection engine :/

**Comment by clawfire** [comment]
I implemented something using https://github.com/faisalman/ua-parser-js which seems to work just fine 😃 
Thanks for the pointers

**Pull request closed without merging**
