### PR TITLE
docs: Add instructions for CZ

### PR DESCRIPTION
**Pull request by janbrasna**
Link to official cz gov site for digi certs.

### CODE REVIEW

**Comment by clawfire** [comment]
Hey @janbrasna 😃 
Thanks for the contribution 😃  IDK why the test wasn't running but we are clear do go 😃

**Review by clawfire — APPROVED** [review]

**Comment by janbrasna** [comment]
@clawfire 👍 Anytime! Glad to contribute.

(The automation doesn't run before approvals for non-contributors at the time.)

_PS: I've seen .GR and .BE instructions at the other branded sites, not sure if the code for that is elsewhere… but might be worth porting the national instructions for those two countries from that repo as well._

**Comment by clawfire** [comment]
There's a translation engine that goes over the index.html and then generates the translation of all the other pages based on the translation memory it has (and adds new content to translate into it). So the most up-to-date should be the index.html. Other pages don't matter.

**Comment by janbrasna** [comment]
@clawfire Oh my bad, I meant the Belgian and Greek national authorities instructions as per covidpass.doctoranytime.be & covidpass.doctoranytime.gr … that apparently are not present in this main app.

**Comment by clawfire** [comment]
oh yes. I should backport them into the community version of the app. good point.

**Comment by clawfire** [comment]
Opened #300 for this

**Pull request merged**
