### PR TITLE
feat: add greek eudcc info

### PR DESCRIPTION
**Pull request by cfanoulis**
changelog:

- move producthunt badge above FAQ
- copyedits
- Add Greek method of obtaining an EUDCC

### CODE REVIEW

**Comment by clawfire** [comment]
Hey there 😃 

Thanks for the awesome contrib 🥰 . I should have written a CONTRIBUTING file so I would avoid you starting from `main` with many changes already in `develop`. 

I gonna try to port your changes from there. `main` is auto-deployed in production so we use a git-flow approach. Working in `develop` then merge in `main` when making a new release.

**Comment by cfanoulis** [comment]
ah schucks. I can try & rebase the changes on develop tomorrow, no need to repeat ourselves here

**Comment by grischard** [comment]
Superseded in #82

**Comment by cfanoulis** [comment]
alright @clawfire, sorry for taking so long but this should be properly rebased on top of develop now!

**Comment by cfanoulis** [comment]
or not, seems like I broke it whoops

**Comment by clawfire** [comment]
Damn it !

**Comment by cfanoulis** [comment]
this is ready for merge, I don't see any other copy changes I can make (if I find any I can always make a 2nd PR)

**Pull request closed without merging**
