### PR TITLE
Allow image upload

### PR DESCRIPTION
**Pull request by grischard**

### CODE REVIEW

**Comment by grischard** [comment]
Without PDF support; I named it 'screenshot' because vague hints make for the best user experience :p.

**Comment by grischard** [comment]
This shouldn't be merged yet - playing with it a bit more, I run into trouble with `scanImage` where it can't decode codes that worked before...

**Comment by grischard** [comment]
This works on desktop Chrome, but on desktop Safari, scanImage throws an exception:

`SyntaxError: Unexpected token '<'`

No idea what it does on mobile or how to test it.

**Comment by clawfire** [comment]
> This works on desktop Chrome, but on desktop Safari, `scanImage` throws an exception:
> 
> `SyntaxError: Unexpected token '<'`

This happen when the service worker file is 404, the JS try to register then a 404 page content (HTML starting with <HTML usually) and the browser just throw an error.

**Comment by grischard** [comment]
I'm actually getting better results scanning codes like this than with the camera. Should I add text to the FAQ in this PR to suggest trying a static photo?

**Comment by clawfire** [comment]
well, due to how camera decoding works on safari IOS that' totally makes sense. We are forced to handle frame by frame (ergo the service worker doing it). 
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 91.0.4472.114 on Mac OS 10.15.7
Viewport:  1425 x 868 @1x
Language:  fr-LU
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-28--covid19passbook.netlify.app%2F&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=91.0&resolution=1425x868&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-28--covid19passbook.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60ddda82b83cb90008a61255&commentID=60de20f325797a1fd9e3a9d5&resolution=resolved)

**Comment by clawfire** [comment]
I think we cannot have button with icon inside of this "or" structure. It's very confusing 🤔  I'm gonna try something
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 91.0.4472.114 on Mac OS 10.15.7
Viewport:  1425 x 868 @1x
Language:  fr-LU
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-28--covid19passbook.netlify.app%2F&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=91.0&resolution=1425x868&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-28--covid19passbook.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60ddda82b83cb90008a61255&commentID=60de21a5df7bbc229047e5d3&resolution=resolved)

**Pull request merged**
