### PR TITLE
Compressed images, corrected colours

### PR DESCRIPTION
**Pull request by grischard**

### CODE REVIEW

**Comment by grischard** [comment]
This makes the flag blue the same as the background blue - the older image didn't have the "right" EU colours.

**Review by clawfire — COMMENTED** [review]
Thanks for the pictures optimisations, however, optimizing semantic-ui ressources doesn't makes sense. This vendor ressource is outside our project scope and will be updated frequently

**Comment by grischard** [comment]
Ah, I thought that'd be ok since third party libraries are hosted locally. I'm fine with running `svgo` on the resources every time if necessary, or dropping that optimisation, or whatever you prefer.

**Comment by clawfire** [comment]
We're not even sure to stick with it. So far I would prefer droppping this optim and we'll be good to go. I just want to try the e2e signature process before and I'll merge
<details><summary>Browser metadata</summary>





```
Path:      /#feedback
Browser:   Chrome 91.0.4472.114 on Mac OS 10.15.7
Viewport:  1425 x 868 @1x
Language:  fr-LU
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-26--covid19passbook.netlify.app%2F%23feedback&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=91.0&resolution=1425x868&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-26--covid19passbook.netlify.app/#feedback) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60dd878bf7ab2f000880facc&commentID=60de1e52d51fe51c74b51b67&resolution=resolved)

**Comment by grischard** [comment]
Done!

**Comment by clawfire** [comment]
Moving your PR on `develop`. It will be merged to main on the following release

**Review by clawfire — APPROVED** [review]

**Pull request merged**
