### PR TITLE
Add Taiwan's certificate download info

### PR DESCRIPTION
**Pull request by dlackty**
[Taiwan gov adopts EU's certificate format](https://focustaiwan.tw/society/202112270022) and  the download website was just released today. 

I tested the QRCode and it works nicely with this passbook generator.

It will be great if you can add zh locale option to crowdin, and I would help translate it too.

Thanks again for the nice project!

### CODE REVIEW

**Comment by chiu99** [comment]
According to [European Comission](https://ec.europa.eu/commission/presscorner/detail/en/mex_21_7066), holders of certificates issued by Taiwan will be able to use them under the same conditions as holders of an EU Digital COVID Certificate do.

**Comment by dlackty** [comment]
I rebased this PR on `develop` and update the PR accordingly.
@clawfire Would you please have a look on this? Thank you!

**Comment by clawfire** [comment]
Hey guys, sorry I totally missed that notification for a PR. 
Just checking on it right now 😃 

> It will be great if you can add zh locale option to crowdin, and I would help translate it too.

I can add some or all of thoses zh-CN, zh-TW, zh-HK, zh-MO, zh-SG

**Review by clawfire — APPROVED** [review]

**Comment by dlackty** [comment]
`zh-TW` is the only one used by Taiwan users. Let me know when you add it to crowdin. 
Thank you again for the help!

**Comment by clawfire** [comment]
Just added it 😃 
Thanks for your contribution. Will merge in prod EOW. 

BTW, you may want to add `zh-TW` to the `<select />` starting line 260. Please keep it sorted by locale ;)

**Pull request merged**
